version: "3.1"
services:
    mariadb:
      image: mariadb:latest
      container_name: esgi-symfony-cours-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=esgi-symfony-cours
        - MYSQL_USER=esgi-symfony-cours
        - MYSQL_PASSWORD=esgi-symfony-cours
      ports:
        - "8163:3306"

    webserver:
      image: nginx:stable
      container_name: esgi-symfony-cours-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./engine/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8063:80"

    php-fpm:
      build:
        context: engine/php-fpm
      container_name: esgi-symfony-cours-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./engine/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: esgi-symfony-cours-phpmyadmin
      links:
        - mariadb:db
      ports:
        - "8263:80"
      environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root
